#!/usr/bin/env python3
"""Generate OTA encryption/signing keys

Generates two files:
  - firmware/APP/include/ota_keys.h (C header)
  - ota/ota_keys.py (Python key file)

Neither file should be committed to git.
"""

import os
import secrets
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)

C_HEADER_PATH = os.path.join(PROJECT_DIR, "firmware", "APP", "include", "ota_keys.h")
PY_KEYS_PATH = os.path.join(SCRIPT_DIR, "ota_keys.py")


def format_c_array(name: str, data: bytes) -> str:
    hex_bytes = ", ".join(f"0x{b:02X}" for b in data)
    return f"static const uint8_t {name}[{len(data)}] = {{\n    {hex_bytes}\n}};"


def main():
    # Check if keys already exist
    if os.path.exists(C_HEADER_PATH) and os.path.exists(PY_KEYS_PATH):
        print(f"Key files already exist:")
        print(f"  {C_HEADER_PATH}")
        print(f"  {PY_KEYS_PATH}")
        if "--force" not in sys.argv:
            print("Use --force to regenerate")
            sys.exit(1)
        print("--force: regenerating keys")

    # Generate keys
    aes_key = secrets.token_bytes(16)   # AES-128 key
    signing_key = secrets.token_bytes(32)  # HMAC-SHA256 key

    # Write C header
    c_content = f"""\
/*
 * OTA Encryption/Signing Keys
 * AUTO-GENERATED by generate_ota_keys.py - DO NOT COMMIT TO GIT
 */

#ifndef OTA_KEYS_H
#define OTA_KEYS_H

#include <stdint.h>

/* AES-128 encryption key (16 bytes) */
{format_c_array("OTA_AES_KEY", aes_key)}

/* HMAC-SHA256 signing key (32 bytes) */
{format_c_array("OTA_SIGNING_KEY", signing_key)}

#endif /* OTA_KEYS_H */
"""
    os.makedirs(os.path.dirname(C_HEADER_PATH), exist_ok=True)
    with open(C_HEADER_PATH, "w") as f:
        f.write(c_content)
    print(f"Generated: {C_HEADER_PATH}")

    # Write Python keys
    py_content = f"""\
# OTA Encryption/Signing Keys
# AUTO-GENERATED by generate_ota_keys.py - DO NOT COMMIT TO GIT

OTA_AES_KEY = bytes.fromhex("{aes_key.hex()}")
OTA_SIGNING_KEY = bytes.fromhex("{signing_key.hex()}")
"""
    with open(PY_KEYS_PATH, "w") as f:
        f.write(py_content)
    print(f"Generated: {PY_KEYS_PATH}")

    print("\nKey generation complete. Make sure these files are not committed to git.")


if __name__ == "__main__":
    main()
